name: bmi_calculator
description: A new Flutter project.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 0.14.2
  scoped_model: 1.0.1
  flutter_spinkit: ^4.0.0
  web_socket_channel: ^1.0.13
  http: ^0.12.0+2
  google_sign_in: ^4.0.14
  dio: ^3.0.4
  flutter_secure_storage: ^3.3.1+1
  cached_network_image: ^1.1.3
  path_provider: ^1.4.4
  image_gallery_saver: ^1.2.2
  firebase_auth: ^0.15.0+1
  firebase_database: ^3.1.0
  cloud_firestore: ^0.12.10+2
#  connectivity:
#  flutter_secure_storage:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: icomoon
      fonts:
      - asset: assets/fonts/IcoMoon.ttf
