name: bmi_calculator
description: A new Flutter project.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 0.14.2
  scoped_model: 1.0.1
  flutter_spinkit: ^4.0.0
  web_socket_channel: ^1.0.13
  http: ^0.12.0+2
  google_sign_in: ^4.0.11
  dio: ^3.0.4
  flutter_secure_storage: ^3.3.1+1
#  connectivity:
#  flutter_secure_storage:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/mountains.jpg
  fonts:
    - family: icomoon
      fonts:
      - asset: assets/fonts/IcoMoon.ttf
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Display-Black.otf
          weight: 900
